// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjEuvKemJXw-IRXijF5UGnawXaaS5FroU',
    appId: '1:525943493205:web:d90d27e2a18ff8c51efadc',
    messagingSenderId: '525943493205',
    projectId: 'fire-76300',
    authDomain: 'fire-76300.firebaseapp.com',
    storageBucket: 'fire-76300.firebasestorage.app',
    measurementId: 'G-DYHW7B5FP1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsoWGS0dbHCb0vNQ2lxa63un7_1kvZqDc',
    appId: '1:525943493205:android:ea088749b601ef071efadc',
    messagingSenderId: '525943493205',
    projectId: 'fire-76300',
    storageBucket: 'fire-76300.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6deBjpuP7vQ-sW_VRuzNIkDTeCEkiiQY',
    appId: '1:525943493205:ios:38532c37cf61f2581efadc',
    messagingSenderId: '525943493205',
    projectId: 'fire-76300',
    storageBucket: 'fire-76300.firebasestorage.app',
    iosBundleId: 'com.example.googlesignin',
  );
}
